### ISSUE TITLE
catalogue upload

### ISSUE THREAD

**Issue by amarkalale** [humbhionline/id.app#13]
Provide this option in seperate tab/page and not in same screen where address etc are shown.

**Comment by venkatramanm** [comment]
Seemed natural to upload in the context of a store. Need more thought to pull out to another screen

**Comment by venkatramanm** [comment]
One option is to have a button at facility level to say manage catalog and take to an xls like screen to manage the list of items. This could force us to persist and keep in our db in a simple format and in full beckn format. The Seller App was made for this purpose. May be the list screen there is sufficient.

**Comment by venkatramanm** [comment]
New facility catalog upload provided as separate  screen
